# TODO: 补充docker compose配置文件

version: "3"
services:
  app:
    restart: always
    container_name: app
    build: . 
    command: >
      bash -c
      "python manage.py makemigrations && python manage.py migrate --settings=YY.settings --fake post&&
      DJANGO_SETTINGS_MODULE=YY.settings gunicorn -w4 -b 0.0.0.0:8000 --log-level=debug YY.wsgi"
    expose:
      - "8000"
    depends_on:
      - mysql
    networks:
      - web_network
      - db_network
  mysql:
    container_name: mysql
    image: mysql:8.1
    volumes:
      - /home/ubuntu/mysql:/var/lib/mysql
    expose:
      - "3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=django
      - TZ=Asia/Shanghai
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    networks:
      - db_network
  celery:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=YY.settings
    command: celery -A YY worker -l info
    volumes:
      - .:/code
    depends_on:
      - app
      - mysql
    networks:
      - web_network
      - db_network

  celerybeat:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=YY.settings
    command: celery -A YY beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/code
    depends_on:
      - app
      - mysql
      - redis
    restart: always  
    networks:
      - web_network
      - db_network


  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - web_network
      - db_network
  nginx:
    container_name: nginx
    restart: always
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - static-volume:/code/static
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - web_network

networks:
  web_network:
    driver: bridge
  db_network:
    driver: bridge
    
volumes:
  static-volume:
